name: data_vault_pro
description: Local-first multi-platform data analysis
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Local Database
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  
  # File Processing
  excel: ^4.0.6
  csv: ^6.0.0
  file_picker: ^8.1.2
  pdfrx: ^1.0.88
  
  # Desktop
  desktop_drop: ^0.4.4
  
  # Charts
  fl_chart: ^0.69.0
  
  # UI/Animations
  animations: ^2.0.11
  
  # Ads
  google_mobile_ads: ^5.2.0
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
